### ISSUE TITLE
Code for generating simulation data

### ISSUE THREAD

**Issue by jleechung** [pachterlab/JBMMCP_2023#1]
Hi,

Is the splatter code for generating the simulated checkerboard and stripe data available? The [links](https://github.com/pachterlab/JBMMCKP_2023/blob/74078ee8bb20f176a29ba8d8dfda215d99584a95/notebooks/cdx-simulation.Rmd#L41) in the markdown seem to be empty - not sure if I'm missing something or looking in the wrong place. Otherwise, if the expression matrices corresponding to the simulated datasets are available and can be shared, that would be great too. 

Thank you!
Joseph

**Comment by kayla-jackson** [comment]
Hi @jleechung, I've uploaded code to regenerate the simulated data. So sorry for the omission and delay in my reply. 

The scripts are in [`notebooks/make-*-data.R`](https://github.com/pachterlab/JBMMCKP_2023/tree/0937df805f7409d84fe117c971af4e30d1d4d96a/notebooks)

**Comment by jleechung** [comment]
Thank you @kayla-jackson!
